### ISSUE TITLE
Review Result.unwrap

### ISSUE THREAD

**Issue by civilcode-pairing** [civilcode/acme-platform#110]
- [ ] Is Result.unwrap blindly unwrapping a payload with the assume it is ok
- [ ] Would `Result.unwrap_ok` be better?
- [ ] Do we really need a `Result.map`?

**Comment by frahugo** [comment]
We should always consider unwrapping a type as a smell: 

http://blog.ploeh.dk/2019/02/04/how-to-get-the-value-out-of-the-monad/

But if we are forced to, then use `Result.unwrap!`, unwraps a `{:ok, term}` only.
