### ISSUE TITLE
Set-up dev environment so we can use :observer

### ISSUE THREAD

**Issue by frahugo** [civilcode/acme-platform#51]

**Comment by bokay** [comment]
After a quick look
- I don't know yet if `wobserver` allows to kill a process. If so, that might be the simplest solution

- There are also command line tools to replicating what the observer does: https://github.com/zhongwencool/observer_cli

- We can install a X11 server locally (xQuartz) and run the observer on the container. Possibly by running docker-compose with `-e DISPLAY=docker.for.mac.localhost:0`. However, erlang is not installed with GTK support currently in the docker images we currently use.

**Comment by nicholasjhenry** [comment]
Let's go with https://github.com/shinyscorpion/wobserver for now. This gets us 99% there :-)

**Comment by bokay** [comment]
@frahugo @nicholasjhenry 
- Not maintained - 2 years ago
- Install from a fork require the source
- Not possible to integrate with Phoenix anymore
- Standalone install is working, but require an open port
- Cowboy 1 and others dependencies deprecated dependencies (from the output, the erlang dependency `websocker_client` could be updated and rely currently on deprecated functions in Erlang)
- Installation from root project not possible, install from an app is working though

Should we continue with `wobserver`?

**Comment by nicholasjhenry** [comment]
Resolved by #114
