### ISSUE TITLE
Losing bind mounts on Docker after file renames

### ISSUE THREAD

**Issue by nicholasjhenry** [civilcode/acme-platform#77]

**Comment by frahugo** [comment]
Some reading on mounts: https://markshust.com/2018/01/30/performance-tuning-docker-mac/

**Comment by bgracie** [comment]
Attempt 1 (use only bind mount, not volume): 
https://github.com/civilcode/giverny-platform/pull/618

**Comment by bgracie** [comment]
Attempt 2 (run docker on a linux VM): 
https://github.com/civilcode/acme-platform/issues/145

**Comment by bgracie** [comment]
Attempt 3 (use docker-sync instead of bind mount)

https://github.com/civilcode/giverny-platform/issues/646

**Comment by bgracie** [comment]
Success with Attempt 3
